export const menuList = [
    {
        id: 1,
        name: "dashboards",
        path: "#",
        icon: "feather-airplay",
        permissionKey: "dashboard",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 101,
                name: "CRM Dashboard",
                path: "/",
                subdropdownMenu: false,
                permissionKey: "dashboard",
                permissionAction: "view",
            },
        ],
    },
    {
        id: 2,
        name: "applications",
        path: "#",
        icon: "feather-send",
        permissionKey: "applications",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 201,
                name: "Tasks",
                path: "/applications/tasks",
                subdropdownMenu: false,
                permissionKey: "tasks",
                permissionAction: "view",
            },
            {
                id: 201,
                name: "Chats",
                path: "/applications/chat",
                subdropdownMenu: false,
                permissionKey: "tasks",
                permissionAction: "view",
            },
            {
                id: 202,
                name: "Notes",
                path: "/applications/notes",
                subdropdownMenu: false,
                permissionKey: "notes",
                permissionAction: "view",
            },
            {
                id: 203,
                name: "My Timelogs",
                path: "/applications/my-timesheet",
                subdropdownMenu: false,
                permissionKey: "timelogs",
                permissionAction: "view",
            },
            {
                id: 204,
                name: "Team Timelogs",
                path: "/applications/team-timesheet",
                subdropdownMenu: false,
                permissionKey: "timelogs",
                permissionAction: "view",
            },
            {
                id: 205,
                name: "Storage",
                path: "/applications/storage",
                subdropdownMenu: false,
                permissionKey: "storage",
                permissionAction: "view",
            },
           
        ],

    },
    {
        id: 20,
        name: "weekly-plans",
        path: "#",
        icon: "feather-clock",
        permissionKey: "weekly_plan",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 701,
                name: "Weekly Plan List",
                path: "/weekly-plans",
                subdropdownMenu: false,
                permissionKey: "weekly_plan",
                permissionAction: "view",
            },
            {
                id: 702,
                name: "Create Weekly Plan",
                path: "/weekly-plans/create",
                subdropdownMenu: false,
                permissionKey: "weekly_plan",
                permissionAction: "create",
            },
           
        ],

    },
    
    {
        id: 3,
        name: "clients",
        path: "#",
        icon: "feather-user-plus",
        permissionKey: "clients",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 301,
                name: "Clients List",
                path: "/clients/list",
                subdropdownMenu: false,
                permissionKey: "clients",
                permissionAction: "view",
            },
            {
                id: 302,
                name: "Create Client",
                path: "/clients/create",
                subdropdownMenu: false,
                permissionKey: "clients",
                permissionAction: "create",
            },
        ],
    },
    {
        id: 4,
        name: "projects",
        path: "#",
        icon: "feather-briefcase",
        permissionKey: "projects",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 401,
                name: "Projects List",
                path: "/projects/list",
                subdropdownMenu: false,
                permissionKey: "projects",
                permissionAction: "view",
            },
            {
                id: 402,
                name: "Create Project",
                path: "/projects/create",
                subdropdownMenu: false,
                permissionKey: "projects",
                permissionAction: "create",
            },
            {
                id: 403,
                name: "Members Create",
                path: "/projects/members/create",
                subdropdownMenu: false,
                permissionKey: "projects",
                permissionAction: "edit",
            },
        ],
    },
    {
        id: 15,
        name: "Meta",
        path: "#",
        icon: "feather-facebook",
        permissionKey: "teams",
        permissionAction: "view",
        dropdownMenu: [{
                id: 501,
                name: "Posts",
                path: "/meta/posts/list",
                subdropdownMenu: false,
                permissionKey: "teams",
                permissionAction: "view",
            },
            // {
            //     id: 502,
            //     name: "Create Post",
            //     path: "/meta/posts/create",
            //     subdropdownMenu: false,
            //     permissionKey: "teams",
            //     permissionAction: "view",
            // },
            // {
            //     id: 503,
            //     name: "Scheduled Posts",
            //     path: "/meta/posts/scheduled",
            //     subdropdownMenu: false,
            //     permissionKey: "teams",
            //     permissionAction: "view",
            // },
            // {
            //     id: 504,
            //     name: "All Leads",
            //     path: "/meta/posts/leads",
            //     subdropdownMenu: false,
            //     permissionKey: "teams",
            //     permissionAction: "view",
            // },
            {
                id: 505,
                name: "Lead Forms",
                path: "/meta/forms",
                subdropdownMenu: false,
                permissionKey: "teams",
                permissionAction: "view",
            },
            {
                id: 504,
                name: "Campaigns",
                path: "/meta-ads/campaigns",
                subdropdownMenu: false,
                permissionKey: "teams",
                permissionAction: "view",
            },
        ]
    },
     {
        id: 16,
        name: "SEO",
        path: "#",
        icon: "feather-search",
        permissionKey: "teams",
        permissionAction: "view",
        dropdownMenu: [{
                id: 601,
                name: "SEO Report",
                path: "/seo",
                subdropdownMenu: false,
                permissionKey: "teams",
                permissionAction: "view",
            },
        ]
    },
    
    {
        id: 5,
        name: "teams",
        path: "#",
        icon: "feather-users",
        permissionKey: "teams",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 501,
                name: "Teams List",
                path: "/teams/list",
                subdropdownMenu: false,
                permissionKey: "teams",
                permissionAction: "view",
            },
            {
                id: 502,
                name: "Create Team",
                path: "/teams/create",
                subdropdownMenu: false,
                permissionKey: "teams",
                permissionAction: "create",
            },
        ],
    },
    {
        id: 6,
        name: "roles",
        path: "#",
        icon: "feather-lock",
        permissionKey: "roles",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 601,
                name: "Role List",
                path: "/roles/list",
                subdropdownMenu: false,
                permissionKey: "roles",
                permissionAction: "view",
            },
            {
                id: 602,
                name: "Add Role",
                path: "/roles/create",
                subdropdownMenu: false,
                permissionKey: "roles",
                permissionAction: "create",
            },
        ],
    },
    {
        id: 7,
        name: "departments",
        path: "#",
        icon: "feather-layers",
        permissionKey: "departments",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 701,
                name: "Department List",
                path: "/departments/list",
                subdropdownMenu: false,
                permissionKey: "departments",
                permissionAction: "view",
            },
            {
                id: 702,
                name: "Add Department",
                path: "/departments/create",
                subdropdownMenu: false,
                permissionKey: "departments",
                permissionAction: "create",
            },
        ],
    },
    {
        id: 8,
        name: "users",
        path: "#",
        icon: "feather-user",
        permissionKey: "users",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 801,
                name: "User List",
                path: "/user/list",
                subdropdownMenu: false,
                permissionKey: "users",
                permissionAction: "view",
            },
            {
                id: 802,
                name: "Add User",
                path: "/user/create",
                subdropdownMenu: false,
                permissionKey: "users",
                permissionAction: "create",
            },
            {
                id: 803,
                name: "User Hierarchy",
                path: "/user/hierarchy",
                subdropdownMenu: false,
                permissionKey: "users",
                permissionAction: "view",
            },
        ],
    },
    {
        id: 9,
        name: "settings",
        path: "#",
        icon: "feather-settings",
        permissionKey: "settings",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 901,
                name: "General",
                path: "/settings/general",
                subdropdownMenu: false,
                permissionKey: "settings",
                permissionAction: "view",
            },
        ],
    },
    // {
    //     id: 10,
    //     name: "authentication",
    //     path: "#",
    //     icon: "feather-power",
    //     permissionKey: "authentication",
    //     permissionAction: "view",
    //     dropdownMenu: [],
    // },
    {
        id: 11,
        name: "help center",
        path: "#",
        icon: "feather-life-buoy",
        permissionKey: "help",
        permissionAction: "view",
        dropdownMenu: [
            {
                id: 1101,
                name: "Support",
                path: "#",
                subdropdownMenu: false,
                permissionKey: "help",
                permissionAction: "view",
            },
            {
                id: 1102,
                name: "Knowledge Base",
                path: "/help/knowledgebase",
                subdropdownMenu: false,
                permissionKey: "help",
                permissionAction: "view",
            },
            {
                id: 1103,
                name: "Documentation",
                path: "/documentations",
                subdropdownMenu: false,
                permissionKey: "help",
                permissionAction: "view",
            },
        ],
    },
];